### ISSUE TITLE
microservices with eureka, zuul and hystrix in kubernetes

### ISSUE THREAD

**Issue by babluchandran** [ewolff/microservice-kubernetes#1]
Hi,
Can we move and run the microservices sample(with eureka, zuul and hystrix) to kubernetes? Outside kubernetes environment we can use docker-compose.yml to run our microservices so link between applications can be given in the docker-compose.yml file. So, inside kubernetes environment can we use the same docker-compose.yml?

**Comment by ewolff** [comment]
This should be a ticket for https://github.com/ewolff/microservice .

However:
- I don't really understand why you would configure these tools if you can use the built-in Kubernetes tools.
- For Kubernetes you would need to do the deployment with  `kubectl`. `docker-compose.yml` is not really the right approach AFAIK.

**Comment by ewolff** [comment]
Please reopen in https://github.com/ewolff/microservice . If you have a PR to implement this, I would welcome it.
