### ISSUE TITLE
Como os containers se comunicam?

### ISSUE THREAD

**Issue by matheus-yaml** [ewolff/microservice-kubernetes#10]
Estou estudando sobre orquestar microservices e não entendo de Java. Mas estou tentando pegar o seu exemplo para estudar essa orquestração... Como os containers se comunicam?

I am study about microservices orquestration and i am do not understand about Java/SpringBoot. But i am trying to use you example for study this orquestration... how do containers comunicate?

**Comment by ewolff** [comment]
Please refer to https://github.com/ewolff/microservice-kubernetes#remarks-on-the-code for some details. Also https://practical-microservices.com/recipes.html might help.
