### ISSUE TITLE
minikube v1.26.0 Windows is unhappy with run command used in kubernetes-deploy.sh

### ISSUE THREAD

**Issue by parawanderer** [ewolff/microservice-kubernetes#11]
It appears that the current correct way to create deployments in minikube is `kubectl create deployment` and `kubectl run` only has the effect of creating a pod. 

```
$ ./kubernetes-deploy.sh 
pod/apache created
Error from server (NotFound): deployments.apps "apache" not found
pod/catalog created
Error from server (NotFound): deployments.apps "catalog" not found
pod/customer created
Error from server (NotFound): deployments.apps "customer" not found
pod/order created
Error from server (NotFound): deployments.apps "order" not found
```

I'll go ahead and make a PR for this update. The explanation on educative should probably also be updated, though.

**Comment by ewolff** [comment]
Actually this is a general problem. `run` is outdated. #12  Fixed this. Thanks!
