### ISSUE TITLE
microservice-kubernetes-demo issues

### ISSUE THREAD

**Issue by csandhya8** [ewolff/microservice-kubernetes#2]
Hi ,
I tried to implement the microservice-kubernetes-demo. deployement created and service exposed successfully ,but i dont know how to access the application in UI.Kindly do the needfull

Regards,
Sandhya C

**Comment by ewolff** [comment]
Thanks for reaching out! Did you try `minikube service apache` as it says at https://github.com/ewolff/microservice-kubernetes#run-on-kubernetes ?

**Comment by sekolahlinux** [comment]
hai @ewolff  i wanna ask something to you,  how service on pods comunicate to service on other pods..?
can you explain to me..

thankyou

**Comment by ewolff** [comment]
@sekolahlinux I updated https://github.com/ewolff/microservice-kubernetes/blob/master/README.md#remarks-on-the-code to explain this. Thanks for reaching out!

**Comment by ewolff** [comment]
No update from the reporter of the original issue - closing.
