### ISSUE TITLE
Deploy Container not started: MatchInterPodAffinity

### ISSUE THREAD

**Issue by surco1971** [ewolff/microservice-kubernetes#3]
I tried your microservice application, but it fails to create the deployment container.

The description of the pods, which are all in Pending state, gives the following reason:

kubectl describe pod  apache-3803140054-kdd2w
.....
  Warning  FailedScheduling  2s (x7 over 33s)  default-scheduler  No nodes are available that match all of the following predicates:: MatchInterPodAffinity (3).

My k8s cluster was deployed by rancher:

#kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.4-rancher1", GitCommit:"388022eda0b4ac982c49a4365a622ad6c68979ce", GitTreeState:"clean", BuildDate:"2017-08-17T19:58:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Until now I only deployed ressources using yaml fies, which worked so far.

Any idea, what can be wrong here?

**Comment by ewolff** [comment]
I am afraid I have no idea what is going on there. MatchInterPodAffinity seems to indicate that no node can run the pods to match the required affinity of the pods. I don't think there was anything configured in the scripts concerning affinity between pods.

**Comment by ewolff** [comment]
No further feedback.
