### ISSUE TITLE
how to access changes in index.html file

### ISSUE THREAD

**Issue by Anuradha677** [ewolff/microservice-kubernetes#5]
Hi,

I need to change the index.html file. But I am not able to see the changes in application after deploy the application. I am using gcr.io for docker images. I am using cloud build for rolling update.I have changed the docker file and kubernetes.yaml in below forked directory. 
Anuradha677 / microservice-kubernetes

Please help me on this.

**Comment by ewolff** [comment]
You will need to build the docker images as discussed in https://github.com/ewolff/microservice-kubernetes/blob/master/HOW-TO-RUN.md#build-the-docker-images-optional and then run them https://github.com/ewolff/microservice-kubernetes/blob/master/HOW-TO-RUN.md#run-the-containers . I will close this issue for know. Please raise specific issues if you feel the documentation should be improved.

**Comment by Anuradha677** [comment]
Thanks for response.
I am able to build the docker images in Container Registry.
![image](https://user-images.githubusercontent.com/50099345/65349048-2c214780-dc00-11e9-9321-67829c850196.png)
![image](https://user-images.githubusercontent.com/50099345/65350922-73113c00-dc04-11e9-96cb-e160daf92a74.png)

I am not using minikube as mentioned in below.
https://github.com/ewolff/microservice-kubernetes/blob/master/HOW-TO-RUN.md#run-the-containers
To deploy the application I am using kubectl apply -f microservices.yaml in cloud shell.
The issue here is, I am able to see the updates in catalog, customer microservices, but I want to change in index.html page. I am doing some changes in index.html file, but after Cloud Build Trigger, I am not able to see the changes. The below link has cloud build trigger file.
https://github.com/Anuradha677/microservice-kubernetes/blob/master/cloudbuilder.yaml

**Comment by ewolff** [comment]
`docker-build.sh` should update the Docker images. Afterwards `kubectl apply -f microservices.yaml` should start the new version. As you are able to deploy the original version in this way, I don't see how there can be a bug in the demo as provided. Sorry.

**Comment by Anuradha677** [comment]
Thanks for response. 
Yes, I am able to deploy original version. As per #How To Run Document the deployment is working. But if I want to modify to check the Rolling Update of Kubernetes, how to change index.html. The new version of apache image is getting stored after changing in index.html page. But I could not see the changes. Can you please help me to see my changes in browser?
