### ISSUE TITLE
changes in microservices.yaml file

### ISSUE THREAD

**Issue by sunilmbhoi** [ewolff/microservice-kubernetes#8]
update api version in defination file (microsevices.yaml) from "apps/v1beta1" to "apps/v1". mentioned version is showing issue. 
Also, add instruction in READ.ME file to update docker username in microservices.yaml file so it will fetch images from resprective user docker account.

**Comment by ewolff** [comment]
Thanks for submitting the issue! The instructions to change the Docker account is at https://github.com/ewolff/microservice-kubernetes/blob/master/HOW-TO-RUN.md#build-the-docker-images-optional .
