### ISSUE TITLE
Request method without get or post 

### ISSUE THREAD

**Issue by akondasif** [ewolff/microservice-kubernetes#9]
Hi @ewolff , 

We followed your recommendations from [this issue](https://github.com/ewolff/microservice/issues/28) and found a few instances of request method without get or post 

Source: 
https://github.com/ewolff/microservice-kubernetes/blob/6d04f5a909478f7f0f78a7ab404047a4a6635cd7/microservice-kubernetes-demo/microservice-kubernetes-demo-catalog/src/main/java/com/ewolff/microservice/catalog/web/CatalogController.java#L30

and 

https://github.com/ewolff/microservice-kubernetes/blob/6d04f5a909478f7f0f78a7ab404047a4a6635cd7/microservice-kubernetes-demo/microservice-kubernetes-demo-order/src/main/java/com/ewolff/microservice/order/logic/OrderController.java#L49

**Comment by ewolff** [comment]
As mentioned https://github.com/ewolff/microservice/issues/28#issuecomment-654375293 I don't think this is a security problem. Please reopen if you have different information. Thanks.
